### ISSUE TITLE
Missing image file

### ISSUE THREAD

**Issue by PaulFWatts** [learnable-content/Build-Your-First-Website-HTMLCSS#1]
assets/img/banner-small.jpg is not included in the repo subsequently no image is being displayed at the smaller screen size

**Comment by angelinamolina** [comment]
Hi, thank you for the notice. I have notified the teacher and waiting for the file. Sorry about the inconvenience.

**Comment by PaulFWatts** [comment]
Hi Angela,

No problems.

Thanks for letting me know…

**Comment by angelinamolina** [comment]
Hi Paul, 

Just a quick note to let you know the image has now been added to all repo branches. Please let me know if you come across any other problems. Thanks! :)

**Comment by PaulFWatts** [comment]
Thanks for letting me know Angela…

Big fan of the way you are engaging the customer (in this case me:-) ) Makes me an even bigger fan of Learnable :-)

**Comment by angelinamolina** [comment]
Thanks for the good morning cheer Paul! This makes me so happy to hear, I'll be sure to pass this on to the team. Happy learning! :)
